// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltteeavnkygcgbwlblof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dGVlYXZua3lnY2did2xibG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDk0MTMsImV4cCI6MjA2MDEyNTQxM30.U2jta0EqlzywN7pMDJGH2EyChhNgEpPryjS8mR_FqDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);