# .github/workflows/android-build.yml
name: Android Build

on:
  workflow_dispatch:  # Allows you to manually trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up JDK for Android
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS Login (Optional if using EAS Submit)
        run: eas whoami || echo "Not logged in"

      - name: Run Prebuild
        run: npx expo prebuild --platform android

      - name: EAS Build (Android AAB)
        run: eas build --platform android --profile production --non-interactive

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: ./dist/*.aab
