name: Build and Sign Android App Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Sign AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g react-native-cli

      - name: Apply patch-package fixes           # <-- ADDED
        run: npm run postinstall                  # <-- ADDED

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Decode and save keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore

      - name: Configure signing properties
        run: |
          cat >> android/gradle.properties <<EOF
          MYAPP_UPLOAD_STORE_FILE=release.keystore
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}
          EOF

      - name: Bundle JavaScript
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build release AAB
        run: |
          cd android
          ./gradlew bundleRelease --no-daemon --stacktrace

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 7

      - name: Clean up keystore
        run: rm -f android/app/release.keystore
