
name: Build and Sign Android App Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Sign AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bundle React Native JavaScript
        run: |
          # Create directory structure for assets
          mkdir -p android/app/src/main/assets
          
          # Create JavaScript bundle
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

      - name: Create React Native directory structure
        run: |
          # Create required directories for React Native
          mkdir -p node_modules/@react-native-community/cli-platform-android
          
          # Create placeholder native_modules.gradle file
          cat > node_modules/@react-native-community/cli-platform-android/native_modules.gradle << 'EOF'
          // This is a placeholder file for the build process
          import groovy.json.JsonSlurper

          def reactNativeModuleConfig = [:]
          def applyNativeModulesSettingsGradle = { settings ->
              // No-op function for CI builds
          }
          def applyNativeModulesAppBuildGradle = { project ->
              // No-op function for CI builds
          }

          ext {
              reactNativeModuleConfig = reactNativeModuleConfig
              applyNativeModulesSettingsGradle = this.&applyNativeModulesSettingsGradle
              applyNativeModulesAppBuildGradle = this.&applyNativeModulesAppBuildGradle
          }
          EOF

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Decode keystore
        run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      - name: Build signed .aab
        env:
          KEYSTORE_PATH: release.keystore
          KEYSTORE_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          # Add warning mode to get more details about the Gradle deprecation warnings
          ./gradlew bundleRelease --warning-mode all \
                                  -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
                                  -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
                                  -Pandroid.injected.signing.key.alias=$KEYSTORE_ALIAS \
                                  -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Clean up keystore
        run: rm -f release.keystore
