name: Build and Deploy .aab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        # Install required dependencies
        sudo apt update
        sudo apt install -y unzip wget

        # Download and extract the Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk

        # Set up environment variables
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

        # Accept Android SDK licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install required SDK components
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "tools"

    - name: Install dependencies
      run: npm install

    - name: Build .aab file
      run: |
        cd android
        ./gradlew bundleRelease

    - name: Upload .aab file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
