name: Build and Deploy .aab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk@v2
      with:
        sdk-version: '30'  # Specify your required SDK version
        build-tools-version: '30.0.3'  # Specify build tools version
        android-licenses: yes  # Accept Android SDK licenses

    - name: Install dependencies
      run: npm install

    - name: Build .aab file
      run: |
        cd android
        ./gradlew bundleRelease

    - name: Upload .aab file as artifact
      uses: actions/upload-artifact@v3  # Updated to v3 for compatibility
      with:
        name: app-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
