name: Build Android App and Upload .aab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt update
        sudo apt install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "tools"

    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.5.0
      with:
        # Set the Gradle task to bundleRelease for generating the AAB file
        build-type: bundle
        gradle-task: bundleRelease
        # Optional: Increment the build number
        increment-build-number: true
        # Optional: Provide the package name
        package-name: com.quizora.com
        # Optional: If you have a keystore, pass its content base64 encoded
        keystore-content: ${{ secrets.KEYSTORE_CONTENT }}
        keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
        keystore-alias: ${{ secrets.KEYSTORE_ALIAS }}
        # Optional: Upload to Google Play Store (if you have Play Store API credentials)
        upload-to-play-store: false
        # Optional: Provide the project path if your Android project is in a subdirectory
        project-path: android
        # Optional: Define the output path (default is output.apk)
        output-path: android/app/build/outputs/bundle/release/app-release.aab

    - name: Upload .aab file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
